# Generated by Django 3.1.7 on 2021-04-08 23:42
import csv
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0003_add_golfer_city'),
    ]

    def add_city_data(apps, schema_editor):

        golfers_infile = open("golfersInput.csv", 'r')
        golfers_lines = csv.reader(golfers_infile)
        golfers = list(golfers_lines)

        for golfer in golfers:
            for i in golfer:
                i.strip()

        golfers_infile.close()

        Golfer = apps.get_model('golfer', 'Golfer')

        for name, bdate, city in golfers:
            golfer = Golfer.objects.get(golfer_name=name)
            golfer.golfer_city = city
            golfer.save()

    def remove_city_data(apps, schema_editor):

        Golfer = apps.get_model('golfer', 'Golfer')
        Golfer.objects.update(golfer_city='unknown')

    operations = [
        migrations.RunPython(add_city_data, reverse_code=remove_city_data)
    ]
